"""Initial

Revision ID: 86ff62ab6a2c
Revises: 
Create Date: 2021-03-16 10:05:15.828575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86ff62ab6a2c'
down_revision = None
branch_labels = None
depends_on = None

CourierType = sa.Enum('foot', 'bike', 'car', name='type')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couriers_imports',
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('import_id', name=op.f('pk__couriers_imports'))
    )
    op.create_table('delivery_hours',
    sa.Column('delivery_hours_id', sa.Integer(), nullable=False),
    sa.Column('time_start', sa.Integer(), nullable=False),
    sa.Column('time_finish', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('delivery_hours_id', name=op.f('pk__delivery_hours'))
    )
    op.create_table('orders_imports',
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('import_id', name=op.f('pk__orders_imports'))
    )
    op.create_table('regions',
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('region_numeric_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('region_id', name=op.f('pk__regions'))
    )
    op.create_table('working_hours',
    sa.Column('working_hours_id', sa.Integer(), nullable=False),
    sa.Column('time_start', sa.Integer(), nullable=False),
    sa.Column('time_finish', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('working_hours_id', name=op.f('pk__working_hours'))
    )
    op.create_table('couriers',
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('type', CourierType, nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['couriers_imports.import_id'], name=op.f('fk__couriers__import_id__couriers_imports')),
    sa.PrimaryKeyConstraint('courier_id', 'import_id', name=op.f('pk__couriers'))
    )
    op.create_table('couriers_working_hours',
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.Column('working_hours_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['working_hours_id'], ['working_hours.working_hours_id'], name=op.f('fk__couriers_working_hours__working_hours_id__working_hours')),
    sa.PrimaryKeyConstraint('import_id', 'courier_id', 'working_hours_id', name=op.f('pk__couriers_working_hours'))
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('region', sa.Integer(), nullable=False),
    sa.Column('assignment_time', sa.DateTime(), nullable=True),
    sa.Column('completion_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['orders_imports.import_id'], name=op.f('fk__orders__import_id__orders_imports')),
    sa.PrimaryKeyConstraint('order_id', 'import_id', name=op.f('pk__orders'))
    )
    op.create_table('orders_delivery_hours',
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.Column('delivery_hours_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_hours_id'], ['delivery_hours.delivery_hours_id'], name=op.f('fk__orders_delivery_hours__delivery_hours_id__delivery_hours')),
    sa.PrimaryKeyConstraint('import_id', 'courier_id', 'delivery_hours_id', name=op.f('pk__orders_delivery_hours'))
    )
    op.create_table('couriers_regions',
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['import_id', 'courier_id'], ['couriers.import_id', 'couriers.courier_id'], name=op.f('fk__couriers_regions__import_id_courier_id__couriers')),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], name=op.f('fk__couriers_regions__region_id__regions')),
    sa.PrimaryKeyConstraint('import_id', 'courier_id', 'region_id', name=op.f('pk__couriers_regions'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('couriers_regions')
    op.drop_table('orders_delivery_hours')
    op.drop_table('orders')
    op.drop_table('couriers_working_hours')
    op.drop_table('couriers')
    op.drop_table('working_hours')
    op.drop_table('regions')
    op.drop_table('orders_imports')
    op.drop_table('delivery_hours')
    op.drop_table('couriers_imports')
    CourierType.drop(op.get_bind())
    # ### end Alembic commands ###
